---
- community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    encoding: 'UTF-8'
    template: 'template0'
    login_host: '127.0.0.1'
    login_user: 'postgres'
    port: 5432
  with_items: "{{ postgresql_databases }}"
