---
- ansible.builtin.lineinfile:
    dest: "{{ postgresql_cluster_caminho }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
    mode: 0644
  with_items: "{{ postgresql_configuracoes }}"

- ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_cluster_caminho }}/pg_hba.conf"
    owner: 'postgres'
    group: 'postgres'
    mode: 0600
  when: postgresql_hba | length > 0
