---
- ansible.builtin.file:
    path: "{{ postgresql_cluster_caminho }}"
    owner: 'postgres'
    group: 'postgres'
    state: directory
    mode: 0700

- ansible.builtin.stat:
    path: "{{ postgresql_cluster_caminho }}/PG_VERSION"
  register: cluster_inicializado

- ansible.builtin.shell: |
    /usr/pgsql-{{ postgresql_versao }}/bin/initdb -D {{ postgresql_cluster_caminho }}
  args:
    executable: /bin/bash
  when: not cluster_inicializado.stat.exists
  become: true
  become_user: 'postgres'