---
- ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    owner: 'postgres'
    group: 'postgres'
    state: directory
    mode: 0700

- ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- ansible.builtin.shell: |
    export PGDATA={{ postgresql_data_dir }}
    export PATH=$PATH:{{ postgresql_bin_path }}
    "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: 'postgres'

- ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    state: started
    enabled: yes