---
- ansible.builtin.stat:
    path: '/etc/yum.repos.d/pgdg-redhat-all.repo'
  register: postgresql_repositorio

- ansible.builtin.stat:
    path: "{{ postgresql_cluster_caminho }}/PG_VERSION"
  register: cluster_presente

- ansible.builtin.dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm
    disable_gpg_check: true
  when: ((postgresql_repositorio) and (not cluster_presente.stat.exists))

- ansible.builtin.shell:
    dnf --nogpgcheck -qy module disable postgresql
  when: ((postgresql_repositorio) and (not cluster_presente.stat.exists))

- ansible.builtin.dnf:
    name: 
      - postgresql{{ postgresql_versao }}
      - postgresql{{ postgresql_versao }}-server
      - postgresql{{ postgresql_versao }}-contrib
      - postgresql{{ postgresql_versao }}-libs
    disable_gpg_check: true
  when: ((postgresql_repositorio) and (not cluster_presente.stat.exists))

- ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-setuptools
    disable_gpg_check: true
  when: ((postgresql_repositorio) and (not cluster_presente.stat.exists))

- ansible.builtin.pip:
    name:
      - psycopg2-binary
  when: ((postgresql_repositorio) and (not cluster_presente.stat.exists))
