---
# FIXME: https://github.com/sol7/infra/issues/176
# - ansible.builtin.stat:
#     path: '/etc/yum.repos.d/pgdg-redhat-all.repo'
#   register: postgresql_versao

# - ansible.builtin.stat:
#     path: "{{ caminho_do_cluster }}/PG_VERSION"
#   register: cluster_presente

- ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm
    disable_gpg_check: true
  #when: postgresql_enablerepo and not cluster_presente.stat.exists 

- ansible.builtin.shell:
    dnf -qy module disable postgresql
  #when: postgresql_enablerepo and not postgresql_versao.stat.exists

- ansible.builtin.yum:
    name: 
      - postgresql{{ postgresql_versao }}
      - postgresql{{ postgresql_versao }}-server
      - postgresql{{ postgresql_versao }}-contrib
      - postgresql{{ postgresql_versao }}-libs
    state: present
    update_cache: true
  #when: postgresql_enablerepo and not postgresql_versao.stat.exists

- ansible.builtin.yum:
    name:
      - python3-pip
      - python3-setuptools
    state: present
    update_cache: true
  #when: postgresql_enablerepo and not postgresql_versao.stat.exists

- ansible.builtin.pip:
    name:
      - psycopg2-binary
  #when: postgresql_enablerepo and not postgresql_versao.stat.exists
