---
- ansible.builtin.include_tasks: instalacao.yml
- ansible.builtin.include_tasks: inicializacao.yml
- ansible.builtin.include_tasks: configuracao.yml
- ansible.builtin.include_tasks: bases.yml

- ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    state: restarted

- include_tasks: hotstandby.yml
  when: postgresql_master != ''

- ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    state: restarted
    enabled: true
