---
- community.postgresql.postgresql_slot:
    name: "{{ postgresql_slot_nome }}"
    login_host: "{{ postgresql_master }}"
    port: '5432'
    login_user: 'postgres'
    login_password: 'postgres'
    db: 'bi_machine_data_origins'
    state: present

- ansible.builtin.systemd:
    name: postgresql-{{ postgresql_versao }}
    state: stopped

- ansible.builtin.file:
    path: "{{ postgresql_cluster_caminho }}/"
    state: absent

- ansible.builtin.shell: |
    /usr/pgsql-{{ postgresql_versao }}/bin/pg_basebackup \
      -S {{ postgresql_slot_nome }} \
      -h {{ postgresql_master }} \
      -U postgres \
      -p 5432 \
      -D {{ postgresql_cluster_caminho }} \
      -Fp -P -Xs -Rv
  environment:
    - PGPASSWORD: postgres
  args:
    executable: /bin/bash
  become: true
  become_user: postgres

# - Altera a replicação para asincrona
- ansible.builtin.lineinfile:
    dest: "{{ postgresql_cluster_caminho }}/postgresql.auto.conf"
    state: absent
    regexp: '^primary_slot_name.*'

- ansible.builtin.systemd:
    name: postgresql-{{ postgresql_versao }}
    state: restarted

# - Apaga o slot_replication no servidor master
- community.postgresql.postgresql_slot:
    name: "{{ postgresql_slot_nome }}"
    login_host: "{{ postgresql_master }}"
    port: '5432'
    login_user: 'postgres'
    login_password: 'postgres'
    db: 'bi_machine_data_origins'
    state: absent
