---
# Variable configuration.
- include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution != 'Amazon'

- include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Fedora'

- ansible.builtin.set_fact:
    postgresql_packages: "{{ postgresql_packages | list }}"
  when: postgresql_packages is not defined

- ansible.builtin.set_fact:
    postgresql_version: "{{ postgresql_version }}"
  when: postgresql_version is not defined

- ansible.builtin.set_fact:
    postgresql_daemon: "{{ postgresql_daemon }}"
  when: postgresql_daemon is not defined

- ansible.builtin.set_fact:
    postgresql_data_dir: "{{ postgresql_data_dir }}"
  when: postgresql_data_dir is not defined

- ansible.builtin.set_fact:
    postgresql_bin_path: "{{ postgresql_bin_path }}"
  when: postgresql_bin_path is not defined

- ansible.builtin.set_fact:
    postgresql_config_path: "{{ postgresql_config_path }}"
  when: postgresql_config_path is not defined

- ansible.builtin.set_fact:
    postgresql_unix_socket_directories_mode: >-
      {{ postgresql_unix_socket_directories_mode | default('02775') }}
  when: postgresql_unix_socket_directories_mode is not defined
